### ISSUE TITLE
NI python bindings

### ISSUE THREAD

**Issue by gftabor** [lindemann09/pyForceDAQ#4]
I have a fork of this repo where I configured it to work with the NI python bindings 

https://github.com/ni/nidaqmx-python
instead of the community one
https://github.com/clade/PyDAQmx

I couldn't get PyDAQmx to work under linux but could get the nidaqmx to work. 

If I made a PR so it autodetected which you have installed and supported either library would you accept it?

**Comment by lindemann09** [comment]
Sorry for my later response. 

Your changes to NI python bindings look great. PR would be nice

**Comment by lindemann09** [comment]
see https://github.com/lindemann09/pyForceDAQ/commit/1ed59e7d18b81b7cf33f5ec947bff7085bd54099

**Comment by gftabor** [comment]
Cool. I have not been near the computer and sensor in a while due to lock down. So it's good you did it yourself, waiting on me would have been a while.

**Comment by lindemann09** [comment]
Made couple of changes recently. I hope thinks still work for you. Python 2.7 is not anymore supported.
